# config/packages/security.yaml

security:
  encoders:
    FOS\UserBundle\Model\UserInterface: bcrypt

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
    #in_memory:
    #  memory:
    #    users:
    #      user:  { password: userpass, roles: [ 'ROLE_USER' ] }
    #      admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    fos_userbundle:
      id: fos_user.user_provider.username
  #access_control:
    #- { path: ^/Adherent, roles: ROLE_ADMIN }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    #main_login:
    #    pattern:    ^/login$
    #    anonymous: true
    main:
      pattern: ^/
      form_login:
        provider: fos_userbundle
        csrf_token_generator: security.csrf.token_manager
        default_target_path: /accueil
      anonymous: true
      logout: true
      #  login_path: security_login
      #  check_path: login_check
      #logout:
      #  path:       logout
      #  target:     security_login

  access_control:
    - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY} #, requires_channel: https }
    - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY} #, requires_channel: https }
    - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY} #, requires_channel: https }
    - { path: ^/admin/, roles: ROLE_ADMIN} #, requires_channel: https }


