version: '3'
services:
    apache:
        build: .docker/apache
        container_name: jcebdd_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/jcebdd
        depends_on:
          - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: jcebdd_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: jcebdd
            MYSQL_USER: jcebdd
            MYSQL_PASSWORD: jcebdd

    php:
        build: .docker/php
        container_name: jcebdd_php
        volumes:
          - .:/home/wwwroot/jcebdd
        environment:
          - maildev_host=jcebdd_maildev
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: jcebdd_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: jcebdd_maildev
        ports:
          - 8001:80
